//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechTalk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Register
    {
        public int AId { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public decimal Phone_no { get; set; }
        public string EmailId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Confirm_Password { get; set; }
    }
}
